# Generated by Django 4.1.3 on 2023-08-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_usuario_direccion_usuaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='usuaria',
            new_name='usuario',
        ),
    ]
