# Generated by Django 4.0.4 on 2023-06-02 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='item',
            new_name='producto',
        ),
    ]
