# Generated by Django 4.1.3 on 2023-10-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
